name: Salesforce Deployment
on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch
jobs:
  deploy-lwc-and-apex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version
          
      - name: Install dependencies
        run: |
          # Only run npm install if package.json exists
          if [ -f "package.json" ]; then
            npm install
          else
            echo "No package.json found, skipping npm install"
          fi
        
      - name: Authenticate with Salesforce
        run: |
          echo "${{ secrets.SALESFORCE_AUTH_URL }}" > ./SALESFORCE_AUTH_URL.txt
          sf org login sfdx-url -f ./SALESFORCE_AUTH_URL.txt -a targetOrg
      
      - name: Find Changed Files
        id: changed-files
        run: |
          # Get the previous commit hash
          PREV_COMMIT=$(git rev-parse HEAD~1)
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Comparing changes between $PREV_COMMIT and $CURRENT_COMMIT"
          
          # Create directory for changed files list
          mkdir -p ./changed_files
          
          # Find changed files in force-app/main/default/lwc
          git diff --name-only $PREV_COMMIT $CURRENT_COMMIT -- force-app/main/default/lwc > ./changed_files/lwc_changes.txt
          
          # Find changed files in force-app/main/default/classes
          git diff --name-only $PREV_COMMIT $CURRENT_COMMIT -- force-app/main/default/classes > ./changed_files/apex_changes.txt
          
          # Check if there are any changes to deploy
          HAS_LWC_CHANGES=false
          HAS_APEX_CHANGES=false
          
          if [ -s ./changed_files/lwc_changes.txt ]; then
            echo "Changed LWC files detected:"
            cat ./changed_files/lwc_changes.txt
            HAS_LWC_CHANGES=true
          else
            echo "No LWC changes detected"
          fi
          
          if [ -s ./changed_files/apex_changes.txt ]; then
            echo "Changed Apex files detected:"
            cat ./changed_files/apex_changes.txt
            HAS_APEX_CHANGES=true
          else
            echo "No Apex changes detected"
          fi
          
          if [ "$HAS_LWC_CHANGES" == "true" ] || [ "$HAS_APEX_CHANGES" == "true" ]; then
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
            echo "HAS_LWC_CHANGES=$HAS_LWC_CHANGES" >> $GITHUB_ENV
            echo "HAS_APEX_CHANGES=$HAS_APEX_CHANGES" >> $GITHUB_ENV
          else
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          fi
        
      - name: Deploy Changed Components to Salesforce
        if: env.HAS_CHANGES == 'true'
        run: |
          # Create a manifest file for only changed components
          mkdir -p manifest
          echo '<?xml version="1.0" encoding="UTF-8"?>' > manifest/package.xml
          echo '<Package xmlns="http://soap.sforce.com/2006/04/metadata">' >> manifest/package.xml
          
          # Add LWC components that have changed
          if [ -s ./changed_files/lwc_changes.txt ]; then
            echo '    <types>' >> manifest/package.xml
            
            # Process each changed LWC folder
            cat ./changed_files/lwc_changes.txt | grep -o "force-app/main/default/lwc/[^/]*" | sort | uniq | while read -r LWC_PATH; do
              LWC_NAME=$(basename "$LWC_PATH")
              echo "        <members>$LWC_NAME</members>" >> manifest/package.xml
            done
            
            echo '        <name>LightningComponentBundle</name>' >> manifest/package.xml
            echo '    </types>' >> manifest/package.xml
          fi
          
          # Add Apex classes that have changed
          if [ -s ./changed_files/apex_changes.txt ]; then
            echo '    <types>' >> manifest/package.xml
            
            # Process each changed Apex class
            cat ./changed_files/apex_changes.txt | grep "\.cls$" | while read -r APEX_FILE; do
              APEX_NAME=$(basename "$APEX_FILE" .cls)
              echo "        <members>$APEX_NAME</members>" >> manifest/package.xml
            done
            
            echo '        <name>ApexClass</name>' >> manifest/package.xml
            echo '    </types>' >> manifest/package.xml
          fi
          
          echo '    <version>58.0</version>' >> manifest/package.xml
          echo '</Package>' >> manifest/package.xml
          
          echo "Created deployment manifest:"
          cat manifest/package.xml
          
          # Deploy only the changed components using the manifest
          # Use RunLocalTests if Apex classes are being deployed, otherwise NoTestRun
          if [ "$HAS_APEX_CHANGES" == "true" ]; then
            echo "Deploying with RunLocalTests due to Apex changes"
            sf project deploy start -o targetOrg -l RunLocalTests -x manifest/package.xml --json > deployment_result.json
          else
            echo "Deploying with NoTestRun (LWC only)"
            sf project deploy start -o targetOrg -l NoTestRun -x manifest/package.xml --json > deployment_result.json
          fi
          
      - name: Check Deployment Status
        if: env.HAS_CHANGES == 'true'
        run: |
          DEPLOY_ID=$(cat deployment_result.json | jq -r '.result.id')
          echo "Deployment ID: $DEPLOY_ID"
          
          # Wait and check deployment status until complete
          while true; do
            STATUS=$(sf project deploy report -i $DEPLOY_ID -o targetOrg --json | jq -r '.result.status')
            echo "Current deployment status: $STATUS"
            
            if [ "$STATUS" == "Succeeded" ]; then
              echo "Deployment completed successfully!"
              sf project deploy report -i $DEPLOY_ID -o targetOrg
              break
            elif [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Error" ]; then
              echo "Deployment failed!"
              sf project deploy report -i $DEPLOY_ID -o targetOrg
              exit 1
            fi
            
            echo "Waiting for deployment to complete..."
            sleep 30
          done
      
      - name: Skip Deployment Notice
        if: env.HAS_CHANGES == 'false'
        run: |
          echo "No LWC or Apex changes detected in this commit. Skipping deployment."
